name: Run Travis ci Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '59 * * * *'  # Runs every hour, on the hour
  workflow_dispatch:  # Manual trigger (you can run it manually from GitHub UI)

jobs:
  build:
    runs-on: ubuntu-latest  # Use an Ubuntu runner for the job

    steps:
      - name: Check out the code
        uses: actions/checkout@v2  # This checks out the code from the repository

      - name: Set up Python 3.10
        uses: actions/setup-python@v2  # Set up Python 3.9 in the environment
        with:
          python-version: '3.10'

      - name: Install required packages
        run: |
          pip install requests  # Install necessary Python packages

      - name: Run the Python script
        run: |
          python3 n.py  # Run your Python script (ensure the script is named n.py)
